### ISSUE TITLE
Mismatched tags from concurrent prints

### ISSUE THREAD

**Issue by phiSgr** [JetBrains/kotlin-compiler-server#619]
See `<outStream>\n<errStream></outStream>` in the below output.

---

Easiest solution is to synchronize over `outputStream` in `OutputStreams.kt`

---

https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS44LjEwIiwiY29kZSI6ImltcG9ydCBrb3RsaW54LmNvcm91dGluZXMuKlxuaW1wb3J0IGtvdGxpbi5jb25jdXJyZW50LipcblxuZnVuIG1haW4oKSB7XG4gICAgdmFsIHQxID0gdGhyZWFkIHtcbiAgICAgICAgcmVwZWF0KDUwKSB7XG4gICAgICAgICAgICBwcmludGxuKFwib3V0XCIpXG4gICAgICAgIH1cbiAgICB9XG5cdHZhbCB0MiA9IHRocmVhZCB7XG4gICAgICAgIHJlcGVhdCg1MCkge1xuICAgICAgICAgICAgU3lzdGVtLmVyci5wcmludGxuKFwiZXJyXCIpXG4gICAgICAgIH1cbiAgICB9XG4gICAgdmFsIHQzID0gdGhyZWFkIHtcbiAgICAgICAgcmVwZWF0KDUwKSB7XG4gICAgICAgICAgICBwcmludGxuKFwib3V0XCIpXG4gICAgICAgIH1cbiAgICB9XG5cdHZhbCB0NCA9IHRocmVhZCB7XG4gICAgICAgIHJlcGVhdCg1MCkge1xuICAgICAgICAgICAgU3lzdGVtLmVyci5wcmludGxuKFwiZXJyXCIpXG4gICAgICAgIH1cbiAgICB9XG4gICAgdDEuam9pbigpXG4gICAgdDIuam9pbigpXG4gICAgdDMuam9pbigpXG4gICAgdDQuam9pbigpXG59XG4iLCJwbGF0Zm9ybSI6ImphdmEiLCJhcmdzIjoiIn0=

`{"errors":{"File.kt":[]},"exception":null,"text":"<outStream>out</outStream><errStream>err</errStream><outStream>\nout</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n<outStream>\n</outStream></errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out<errStream></outStream>err</errStream><outStream>\n<errStream></outStream>\nerr<outStream></errStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream><outStream>\n\n</errStream></outStream><errStream>err<outStream>out</errStream></outStream><errStream><outStream>\n\n</errStream></outStream><errStream>err<outStream>out</errStream></outStream><errStream><outStream>\n\n</errStream></outStream><errStream><outStream>errout</errStream></outStream><errStream><outStream>\n\n</errStream></outStream><errStream><outStream>errout</errStream></outStream><errStream><outStream>\n\n</errStream></outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out<errStream></outStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out<errStream></outStream>\n</errStream><outStream>\n</outStream><errStream>err</errStream><outStream>out<errStream></outStream>\n</errStream><outStream>\n<errStream></outStream>err</errStream><outStream>out<errStream>\n</outStream></errStream><outStream>\n<errStream></outStream>err</errStream><outStream>out<errStream>\n</outStream></errStream><outStream>\n<errStream></outStream>err</errStream><outStream><errStream>out\n</outStream></errStream><outStream>\n<errStream></outStream>err</errStream><outStream>out<errStream>\n</outStream></errStream><outStream>\n<errStream></outStream>err</errStream><outStream>out</outStream><errStream>\n</errStream><outStream>\n<errStream>err</errStream></outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out<errStream></outStream>err</errStream><outStream>\n<errStream></outStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n<errStream></outStream>\nerr<outStream></errStream>out\n<errStream></outStream>\n</errStream><outStream>out<errStream></outStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out\nout<errStream>err</outStream></errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err<outStream></errStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err<outStream></errStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n<outStream>out</errStream></outStream><errStream><outStream>err\n</errStream></outStream><errStream>\n<outStream></errStream>out</outStream><errStream>err<outStream></errStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\n</errStream><outStream>out</outStream><errStream>err</errStream><outStream>\n</outStream><errStream>\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\nerr\n</errStream><outStream>out\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\nout\n</outStream>"}`

**Comment by AlexanderPrendota** [comment]
@nikpachoo cc

**Comment by phiSgr** [comment]
Closed by #618
